name: lib

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build library
        run: yarn build
        # TODO: Publish
        # - name: Publish if version has been updated
        #   uses: pascalgn/npm-publish-action@06e0830ea83eea10ed4a62654eeaedafb8bf50fc
        #   with:
        #     tag_name: "v%s"
        #     tag_message: "v%s"
        #     commit_pattern: "^Release (\\S+)"
        #     workspace: "."
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run prettier
        run: yarn prettier